server:
  port: 8010
spring:
  redis:
    database: 0
    host: 120.78.136.80
    port: 6379
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
  mvc:
    static-path-pattern: /static/**

